Description of getEmpty2DDataset
Home > easyupMVPA > getEmpty2DDataset.m
getEmpty2DDataset
PURPOSE
Returns an empty 2D dataset (i.e. for EEG-data).
SYNOPSIS
function [dataset] = getEmpty2DDataset()
DESCRIPTION
 Returns an empty 2D dataset (i.e. for EEG-data).
 Author: Maurice Hollmann
 Date  : 08/07
 Description:
   [dataset] = getEmpty2DDataset()
   Returns an empty 2D dataset (i.e. for EEG-data) , that can be "filled" with content.
   This is aequivalent to getEmpty4DDataset() in 4D case (i.e. fMRI time series).
   Returned sructure:
   dataset.type                   = 'dataset2D';
   dataset.is4D = false;
   dataset.is2D = true;
   dataset.data2D                 = [];
   dataset.chunks                 = [];
   dataset.classIDs               = [];
   dataset.mask                   = [];
   dataset.featureSelectionMap    = [];
   dataset.processingHistory      = {};
 Parameters:
 Returns:
   dataset          -> empty dataset
 Comments:
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
averageFeaturesInROIs Set the mask (1D or 3D) field of a dataset by a given matrix.
doRecursiveFeatureElemination_bootStrap_SVM [DO NOT USE: UNDER DEVELOPEMENT!] Recursively removes features according to SVM classification weights obtained by bootstrapping.
doSearchlightLOOCV_SVM !UNDER CONSTRUCTION! Implements a Searchlight Classification using One Out Cross Validation (LOOCV) with a SVM Classifier (parallel execution).
splitDataset Splits a dataset by selecting the elements defined by given vectors for the two result datasets.
SOURCE CODE
% Returns an empty 2D dataset (i.e. for EEG-data).
%
% Author: Maurice Hollmann
% Date  : 08/07
%
% Description:
%
%   [dataset] = getEmpty2DDataset()
%
%   Returns an empty 2D dataset (i.e. for EEG-data) , that can be "filled" with content.
%   This is aequivalent to getEmpty4DDataset() in 4D case (i.e. fMRI time series).
%
%   Returned sructure:
%
%   dataset.type                   = 'dataset2D';
%   dataset.is4D = false;
%   dataset.is2D = true;
%   dataset.data2D                 = [];
%   dataset.chunks                 = [];
%   dataset.classIDs               = [];
%   dataset.mask                   = [];
%   dataset.featureSelectionMap    = [];
%   dataset.processingHistory      = {};
%
% Parameters:
%
% Returns:
%
%   dataset          -> empty dataset
%
% Comments:
%
function [dataset] = getEmpty2DDataset()
  dataset = {};
  dataset.type = 'dataset2D';
  dataset.is4D = false;
  dataset.is2D = true;
  dataset.data                   = [];
  dataset.chunks                 = [];
  dataset.classIDs               = [];
  dataset.mask                   = [];
  dataset.featureSelectionMap    = [];
  dataset.processingHistory      = {};
end