Description of easyupMVPA_getGlobals
Home > easyupMVPA > easyupMVPA_getGlobals.m
easyupMVPA_getGlobals
PURPOSE
Returns values for global properties in the toolbox.
SYNOPSIS
function [propertyValue] = easyupMVPA_getGlobals(propertyName)
DESCRIPTION
 Returns values for global properties in the toolbox.
 Author: Maurice Hollmann
 Date  : 08/10
 Description:
  Returns global properties. To set properties use : easyupMVPA_setGlobals(propertyName, propertyValue)
  Properties are:
  easyupMVPA_quietMode  - TRUE/FALSE if true all outputs of routines are suppressed
 Parameters:
   propertyName       -> Name of property to be returned
 Returns:
   ok                 -> returns true when setting worked, otherwise false
 Comments:
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
doHighpassFiltering Does the high-pass filtering in sample dimension (i.e. per voxel in fMRI-time series).
doLeaveOneOutCrossValidation_SVM Implements a Leave One Out Cross Validation (LOOCV) using a Support Vector Machine Classifier (parallel execution).
doLinearDetrending Removes linear trends in sample dimension (i.e. per voxel over samples in fMRI-time series).
doRecursiveFeatureElemination_SVM Recursively removes features according to SVM classification weights (parallel execution).
doRecursiveFeatureElemination_SVM_nestedLOOCV ! DEPRECATED ! Recursively removes features according to SVM classification weights from LOOCV.
doRecursiveFeatureElemination_bootstrapping_SVM [DO NOT USE: UNDER DEVELOPEMENT!] Recursively removes features according to SVM classification weights (parallel execution).
doSearchlightLOOCV_SVM !UNDER CONSTRUCTION! Implements a Searchlight Classification using One Out Cross Validation (LOOCV) with a SVM Classifier (parallel execution).
doZScoring Does Z-Scoring in sample dimension (i.e. per voxel over samples in fMRI-time series).
setDataset_data_ByFilelist Set the data field of a dataset by a given list of nifti-files.
SOURCE CODE
% Returns values for global properties in the toolbox.
%
% Author: Maurice Hollmann
% Date  : 08/10
%
% Description:
%  Returns global properties. To set properties use : easyupMVPA_setGlobals(propertyName, propertyValue)
%
%  Properties are:
%
%  easyupMVPA_quietMode  - TRUE/FALSE if true all outputs of routines are suppressed
%
%
%
% Parameters:
%   propertyName       -> Name of property to be returned
%
% Returns:
%   ok                 -> returns true when setting worked, otherwise false
%
%
% Comments:
function [propertyValue] = easyupMVPA_getGlobals(propertyName)
  global propertyStruct;
  if( isfield(propertyStruct, propertyName) )
    propertyValue = propertyStruct.(propertyName);
  else
    disp(['INFO: easyupMVAP_getGlobals: Variable "',propertyName,'" does not exist, returning FALSE !']);
    propertyValue = false;
  end
end