Description of printResultStruct
Home > easyupMVPA > printResultStruct.m
printResultStruct
PURPOSE
Prints the content of the result struct (result of prediction, LOOCV, RFE) on the screen.
SYNOPSIS
function printResultStruct(resultStruct)
DESCRIPTION
 Prints the content of the result struct (result of prediction, LOOCV, RFE) on the screen.
 Author: Maurice Hollmann
 Date  : 09/10
 Description:
   printResultStruct(resultStruct)
   This methods prints the whole info about dataset at the screen.
 Parameters:
   dataset  - the dataset to print info
 Returns:
 Comments:
CROSS-REFERENCE INFORMATION
This function calls:
printResultStruct Prints the content of the result struct (result of prediction, LOOCV, RFE) on the screen.
This function is called by:
doRecursiveFeatureElemination_SVM Recursively removes features according to SVM classification weights (parallel execution).
doRecursiveFeatureElemination_SVM_nestedLOOCV ! DEPRECATED ! Recursively removes features according to SVM classification weights from LOOCV.
doRecursiveFeatureElemination_bootStrap_SVM (UNDER CONSTRUCTION) Recursively removes features according to SVM classification weights obtained by bootstrapping.
printResultStruct Prints the content of the result struct (result of prediction, LOOCV, RFE) on the screen.
SOURCE CODE
% Prints the content of the result struct (result of prediction, LOOCV, RFE) on the screen.
%
% Author: Maurice Hollmann
% Date  : 09/10
%
% Description:
%
%   printResultStruct(resultStruct)
%
%   This methods prints the whole info about dataset at the screen.
%
% Parameters:
%   dataset  - the dataset to print info
%
% Returns:
%
%
% Comments:
%
function printResultStruct(resultStruct)
     disp('*** RESULT STRUCT:  ***');
     disp(['Number of Tests: ', num2str(resultStruct.nmbTests)])
     disp(['Accuracy:        ', num2str(resultStruct.accuracy), ' %'])
     disp(['True Positives:  ', num2str(resultStruct.TP)])
     disp(['True Negatives:  ', num2str(resultStruct.TN)])
     disp(['False Positives: ', num2str(resultStruct.FP)])
     disp(['False Negatives: ', num2str(resultStruct.FN)])
     disp(['Sensitivity:     ', num2str(resultStruct.sensitivity),'  (TP/TP+FN = Proportion of true positives to all positives).'])
     disp(['Specificity:     ', num2str(resultStruct.specificity),'  (TN/TN+FP = Proportion of true negatives to all negatives).'])
     if(isfield(resultStruct, 'infoString'))
       disp(['Additional Info: ', resultStruct.infoString])
     end
     disp('************************');
     if(isfield(resultStruct, 'innerResultStruct') && ~isempty(resultStruct.innerResultStruct))
       disp(' ');
       disp('*** INNER RESULT STRUCT HOLDING ADDITIONAL INFORMATION ***');
       printResultStruct(resultStruct.innerResultStruct);
     end
end