Description of setDataset_data_ByMatrix
Home > easyupMVPA > setDataset_data_ByMatrix.m
setDataset_data_ByMatrix
PURPOSE
Set the data field of a datasets by a given matrix.
SYNOPSIS
function [dataset] = setDataset_data_ByMatrix(dataset, dataMatrix)
DESCRIPTION
 Set the data field of a datasets by a given matrix.
 Author: Maurice Hollmann
 Date  : 08/10
 Description:
   [dataset] = setDataset_data_ByMatrix(dataset, matrix2D)
   This methods sets the data (2D or 4D) for the given dataset and checks the outcome.
 Parameters:
   dataset     - the datset to set the data2D field
   dataMatrix  - a 2D or 4D matrix containing the whole data (nmbFeatures x nmbSamples)
 Returns:
   dataset   - the datset with included data2D
 Comments:
CROSS-REFERENCE INFORMATION
This function calls:
checkDataset Checks a given dataset for correctness (i.e. size of defined matrices).
This function is called by:
averageFeaturesInROIs Set the mask (1D or 3D) field of a dataset by a given matrix.
doRecursiveFeatureElemination_bootStrap_SVM (UNDER CONSTRUCTION) Recursively removes features according to SVM classification weights obtained by bootstrapping.
SOURCE CODE
% Set the data field of a datasets by a given matrix.
%
% Author: Maurice Hollmann
% Date  : 08/10
%
% Description:
%
%   [dataset] = setDataset_data_ByMatrix(dataset, matrix2D)
%
%   This methods sets the data (2D or 4D) for the given dataset and checks the outcome.
%
% Parameters:
%   dataset     - the datset to set the data2D field
%   dataMatrix  - a 2D or 4D matrix containing the whole data (nmbFeatures x nmbSamples)
%
% Returns:
%   dataset   - the datset with included data2D
%
% Comments:
%
function [dataset] = setDataset_data_ByMatrix(dataset, dataMatrix)
  if(~isfield(dataset, 'type'))
    error('Given dataset has not defined the field "type" !');
  end
  if( ~exist('dataset','var') || ~exist('dataMatrix','var') )
    error('Usage of setDataset_data_ByMatrix: [dataset] = setDataset_data_ByMatrix(dataset, dataMatrix)');
  end
  if(isempty(dataMatrix))
    error('Given matrix2D is empty!');
  end
  dataset.data = dataMatrix;
  if(~checkDataset(dataset))
    disp('WARNING: setDataset_data_ByMatrix: In the current state the dataset is not suitable for further processing, please see messages before!');
  end
end