Description of splitDataset
Home > easyupMVPA > splitDataset.m
splitDataset
PURPOSE
Splits a dataset by selecting the elements defined by given vectors for the two result datasets.
SYNOPSIS
function [dataset1, dataset2] = splitDataset(dataset, vectorDS1, vectorDS2)
DESCRIPTION
 Splits a dataset by selecting the elements defined by given vectors for the two result datasets.
 Author: Maurice Hollmann
 Date  : 08/10
 Description:
 Lowlevel function for splitting a dataset by giving two non-overlaping vectors. The vectors contain zeros and ones, where
 one means the sample is included and zero it is not.
 Parameters:
   dataset     - the dataset to split
   vectorDS1   - a vector of the length of number of samples containing zeros and ones, elements with ones will be included in ds1
   vectorDS2   - a vector of the length of number of samples containing zeros and ones, elements with ones will be included in ds2
 Returns:
   dataset    - the filtered datset
 Comments:
CROSS-REFERENCE INFORMATION
This function calls:
getEmpty2DDataset Returns an empty 2D dataset (i.e. for EEG-data).
getEmpty4DDataset Returns an empty 4D dataset (i.e. for fMRI-data).
This function is called by:
doLeaveOneOutCrossValidation_SVM Implements a Leave One Out Cross Validation (LOOCV) using a Support Vector Machine Classifier (parallel execution).
doRecursiveFeatureElemination_SVM Recursively removes features according to SVM classification weights (parallel execution).
doRecursiveFeatureElemination_SVM_nestedLOOCV ! DEPRECATED ! Recursively removes features according to SVM classification weights from LOOCV.
doRecursiveFeatureElemination_bootstrapping_SVM [DO NOT USE: UNDER DEVELOPEMENT!] Recursively removes features according to SVM classification weights (parallel execution).
SOURCE CODE
% Splits a dataset by selecting the elements defined by given vectors for the two result datasets.
%
% Author: Maurice Hollmann
% Date  : 08/10
%
% Description:
% Lowlevel function for splitting a dataset by giving two non-overlaping vectors. The vectors contain zeros and ones, where
% one means the sample is included and zero it is not.
%
%
% Parameters:
%   dataset     - the dataset to split
%   vectorDS1   - a vector of the length of number of samples containing zeros and ones, elements with ones will be included in ds1
%   vectorDS2   - a vector of the length of number of samples containing zeros and ones, elements with ones will be included in ds2
%
% Returns:
%   dataset    - the filtered datset
%
% Comments:
%
function [dataset1, dataset2] = splitDataset(dataset, vectorDS1, vectorDS2)
  %check if the vectors are overlapping
  sumV = vectorDS1+vectorDS2;
  if(~(length(vectorDS1)==length(vectorDS2)) || sum(sumV>1))
   error('The vectors describing the split must be of equal length and non-overlapping!');
  end
  if(dataset.is4D)
    dataset1 = getEmpty4DDataset();
    dataset2 = getEmpty4DDataset();
    vectorDS1 = logical(vectorDS1);
    vectorDS2 = logical(vectorDS2);
    dataset1.data                  = dataset.data(:,:,:, vectorDS1);
    dataset1.chunks                = dataset.chunks(vectorDS1);
    dataset1.classIDs              = dataset.classIDs(vectorDS1);
    dataset1.mask                  = dataset.mask;
    dataset1.featureSelectionMap   = dataset.featureSelectionMap;
    dataset1.dataFilelist          = dataset.dataFilelist;
    dataset2.data                  = dataset.data(:,:,:, vectorDS2);
    dataset2.chunks                = dataset.chunks(vectorDS2);
    dataset2.classIDs              = dataset.classIDs(vectorDS2);
    dataset2.mask                  = dataset.mask;
    dataset2.featureSelectionMap   = dataset.featureSelectionMap;
    dataset2.dataFilelist          = dataset.dataFilelist;
  elseif(dataset.is2D)
    dataset1 = getEmpty2DDataset();
    dataset2 = getEmpty2DDataset();
    vectorDS1 = logical(vectorDS1);
    vectorDS2 = logical(vectorDS2);
    dataset1.data                = dataset.data(:,vectorDS1);
    dataset1.chunks              = dataset.chunks(vectorDS1);
    dataset1.classIDs            = dataset.classIDs(vectorDS1);
    dataset1.mask                = dataset.mask;
    dataset1.featureSelectionMap = dataset.featureSelectionMap;
    dataset2.data                = dataset.data(:, vectorDS2);
    dataset2.chunks              = dataset.chunks(vectorDS2);
    dataset2.classIDs            = dataset.classIDs(vectorDS2);
    dataset2.mask                = dataset.mask;
    dataset2.featureSelectionMap = dataset.featureSelectionMap;
  else
    disp('SPLIT DATASET: Please check the dataset: "type" is not correctly defined!');
  end
end